//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace TrafficPolice.UI.Droid.TrafficPoliceService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_ITrafficPoliceService", Namespace="http://tempuri.org/")]
    public partial class TrafficPoliceService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetUserByIdAndPassOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDriverOwnerByIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback getRegByRegNumOperationCompleted;
        
        private System.Threading.SendOrPostCallback addPenaltyToDriverOwnerOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public TrafficPoliceService() {
            this.Url = "http://localhost:9607/TrafficPoliceService.svc";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetUserByIdAndPassCompletedEventHandler GetUserByIdAndPassCompleted;
        
        /// <remarks/>
        public event GetDriverOwnerByIdCompletedEventHandler GetDriverOwnerByIdCompleted;
        
        /// <remarks/>
        public event getRegByRegNumCompletedEventHandler getRegByRegNumCompleted;
        
        /// <remarks/>
        public event addPenaltyToDriverOwnerCompletedEventHandler addPenaltyToDriverOwnerCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ITrafficPoliceService/GetUserByIdAndPass", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public User GetUserByIdAndPass([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string id, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string password) {
            object[] results = this.Invoke("GetUserByIdAndPass", new object[] {
                        id,
                        password});
            return ((User)(results[0]));
        }
        
        /// <remarks/>
        public void GetUserByIdAndPassAsync(string id, string password) {
            this.GetUserByIdAndPassAsync(id, password, null);
        }
        
        /// <remarks/>
        public void GetUserByIdAndPassAsync(string id, string password, object userState) {
            if ((this.GetUserByIdAndPassOperationCompleted == null)) {
                this.GetUserByIdAndPassOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUserByIdAndPassOperationCompleted);
            }
            this.InvokeAsync("GetUserByIdAndPass", new object[] {
                        id,
                        password}, this.GetUserByIdAndPassOperationCompleted, userState);
        }
        
        private void OnGetUserByIdAndPassOperationCompleted(object arg) {
            if ((this.GetUserByIdAndPassCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUserByIdAndPassCompleted(this, new GetUserByIdAndPassCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ITrafficPoliceService/GetDriverOwnerById", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public DriverOwner GetDriverOwnerById([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string id) {
            object[] results = this.Invoke("GetDriverOwnerById", new object[] {
                        id});
            return ((DriverOwner)(results[0]));
        }
        
        /// <remarks/>
        public void GetDriverOwnerByIdAsync(string id) {
            this.GetDriverOwnerByIdAsync(id, null);
        }
        
        /// <remarks/>
        public void GetDriverOwnerByIdAsync(string id, object userState) {
            if ((this.GetDriverOwnerByIdOperationCompleted == null)) {
                this.GetDriverOwnerByIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDriverOwnerByIdOperationCompleted);
            }
            this.InvokeAsync("GetDriverOwnerById", new object[] {
                        id}, this.GetDriverOwnerByIdOperationCompleted, userState);
        }
        
        private void OnGetDriverOwnerByIdOperationCompleted(object arg) {
            if ((this.GetDriverOwnerByIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDriverOwnerByIdCompleted(this, new GetDriverOwnerByIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ITrafficPoliceService/getRegByRegNum", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Registration getRegByRegNum([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string regNum) {
            object[] results = this.Invoke("getRegByRegNum", new object[] {
                        regNum});
            return ((Registration)(results[0]));
        }
        
        /// <remarks/>
        public void getRegByRegNumAsync(string regNum) {
            this.getRegByRegNumAsync(regNum, null);
        }
        
        /// <remarks/>
        public void getRegByRegNumAsync(string regNum, object userState) {
            if ((this.getRegByRegNumOperationCompleted == null)) {
                this.getRegByRegNumOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetRegByRegNumOperationCompleted);
            }
            this.InvokeAsync("getRegByRegNum", new object[] {
                        regNum}, this.getRegByRegNumOperationCompleted, userState);
        }
        
        private void OngetRegByRegNumOperationCompleted(object arg) {
            if ((this.getRegByRegNumCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getRegByRegNumCompleted(this, new getRegByRegNumCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ITrafficPoliceService/addPenaltyToDriverOwner", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string addPenaltyToDriverOwner([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Penalty pen) {
            object[] results = this.Invoke("addPenaltyToDriverOwner", new object[] {
                        pen});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void addPenaltyToDriverOwnerAsync(Penalty pen) {
            this.addPenaltyToDriverOwnerAsync(pen, null);
        }
        
        /// <remarks/>
        public void addPenaltyToDriverOwnerAsync(Penalty pen, object userState) {
            if ((this.addPenaltyToDriverOwnerOperationCompleted == null)) {
                this.addPenaltyToDriverOwnerOperationCompleted = new System.Threading.SendOrPostCallback(this.OnaddPenaltyToDriverOwnerOperationCompleted);
            }
            this.InvokeAsync("addPenaltyToDriverOwner", new object[] {
                        pen}, this.addPenaltyToDriverOwnerOperationCompleted, userState);
        }
        
        private void OnaddPenaltyToDriverOwnerOperationCompleted(object arg) {
            if ((this.addPenaltyToDriverOwnerCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.addPenaltyToDriverOwnerCompleted(this, new addPenaltyToDriverOwnerCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/TrafficPoliceWcfHost.Model")]
    public partial class User {
        
        private string firstNameField;
        
        private bool isTrafficPolicemanField;
        
        private bool isTrafficPolicemanFieldSpecified;
        
        private string lastNameField;
        
        private string secondNameField;
        
        private long userIdField;
        
        private bool userIdFieldSpecified;
        
        private string userPasswordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        public bool IsTrafficPoliceman {
            get {
                return this.isTrafficPolicemanField;
            }
            set {
                this.isTrafficPolicemanField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsTrafficPolicemanSpecified {
            get {
                return this.isTrafficPolicemanFieldSpecified;
            }
            set {
                this.isTrafficPolicemanFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string SecondName {
            get {
                return this.secondNameField;
            }
            set {
                this.secondNameField = value;
            }
        }
        
        /// <remarks/>
        public long UserId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool UserIdSpecified {
            get {
                return this.userIdFieldSpecified;
            }
            set {
                this.userIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string UserPassword {
            get {
                return this.userPasswordField;
            }
            set {
                this.userPasswordField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/TrafficPoliceWcfHost.Model")]
    public partial class Registration {
        
        private string carColorField;
        
        private int carCubageField;
        
        private bool carCubageFieldSpecified;
        
        private int carHpField;
        
        private bool carHpFieldSpecified;
        
        private string carManufacturerField;
        
        private string carModelField;
        
        private string carTypeField;
        
        private string carVinField;
        
        private System.DateTime civilInsuranceEndDateField;
        
        private bool civilInsuranceEndDateFieldSpecified;
        
        private System.DateTime civilInsuranceStartDateField;
        
        private bool civilInsuranceStartDateFieldSpecified;
        
        private string civilInsurerField;
        
        private System.DateTime damageInsuranceEndDateField;
        
        private bool damageInsuranceEndDateFieldSpecified;
        
        private System.DateTime damageInsuranceStartDateField;
        
        private bool damageInsuranceStartDateFieldSpecified;
        
        private string damageInsurerField;
        
        private long driverOwnerIdField;
        
        private bool driverOwnerIdFieldSpecified;
        
        private System.DateTime firstRegDateField;
        
        private bool firstRegDateFieldSpecified;
        
        private bool hasCivilInsuranceField;
        
        private bool hasCivilInsuranceFieldSpecified;
        
        private bool hasDamageInsuranceField;
        
        private bool hasDamageInsuranceFieldSpecified;
        
        private bool hasVignetteField;
        
        private bool hasVignetteFieldSpecified;
        
        private System.DateTime recentRegDateField;
        
        private bool recentRegDateFieldSpecified;
        
        private string regNumField;
        
        private System.DateTime vignetteValidUntilField;
        
        private bool vignetteValidUntilFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CarColor {
            get {
                return this.carColorField;
            }
            set {
                this.carColorField = value;
            }
        }
        
        /// <remarks/>
        public int CarCubage {
            get {
                return this.carCubageField;
            }
            set {
                this.carCubageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CarCubageSpecified {
            get {
                return this.carCubageFieldSpecified;
            }
            set {
                this.carCubageFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int CarHp {
            get {
                return this.carHpField;
            }
            set {
                this.carHpField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CarHpSpecified {
            get {
                return this.carHpFieldSpecified;
            }
            set {
                this.carHpFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CarManufacturer {
            get {
                return this.carManufacturerField;
            }
            set {
                this.carManufacturerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CarModel {
            get {
                return this.carModelField;
            }
            set {
                this.carModelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CarType {
            get {
                return this.carTypeField;
            }
            set {
                this.carTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CarVin {
            get {
                return this.carVinField;
            }
            set {
                this.carVinField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime CivilInsuranceEndDate {
            get {
                return this.civilInsuranceEndDateField;
            }
            set {
                this.civilInsuranceEndDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CivilInsuranceEndDateSpecified {
            get {
                return this.civilInsuranceEndDateFieldSpecified;
            }
            set {
                this.civilInsuranceEndDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime CivilInsuranceStartDate {
            get {
                return this.civilInsuranceStartDateField;
            }
            set {
                this.civilInsuranceStartDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CivilInsuranceStartDateSpecified {
            get {
                return this.civilInsuranceStartDateFieldSpecified;
            }
            set {
                this.civilInsuranceStartDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CivilInsurer {
            get {
                return this.civilInsurerField;
            }
            set {
                this.civilInsurerField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DamageInsuranceEndDate {
            get {
                return this.damageInsuranceEndDateField;
            }
            set {
                this.damageInsuranceEndDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DamageInsuranceEndDateSpecified {
            get {
                return this.damageInsuranceEndDateFieldSpecified;
            }
            set {
                this.damageInsuranceEndDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DamageInsuranceStartDate {
            get {
                return this.damageInsuranceStartDateField;
            }
            set {
                this.damageInsuranceStartDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DamageInsuranceStartDateSpecified {
            get {
                return this.damageInsuranceStartDateFieldSpecified;
            }
            set {
                this.damageInsuranceStartDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DamageInsurer {
            get {
                return this.damageInsurerField;
            }
            set {
                this.damageInsurerField = value;
            }
        }
        
        /// <remarks/>
        public long DriverOwnerId {
            get {
                return this.driverOwnerIdField;
            }
            set {
                this.driverOwnerIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DriverOwnerIdSpecified {
            get {
                return this.driverOwnerIdFieldSpecified;
            }
            set {
                this.driverOwnerIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime FirstRegDate {
            get {
                return this.firstRegDateField;
            }
            set {
                this.firstRegDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FirstRegDateSpecified {
            get {
                return this.firstRegDateFieldSpecified;
            }
            set {
                this.firstRegDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool HasCivilInsurance {
            get {
                return this.hasCivilInsuranceField;
            }
            set {
                this.hasCivilInsuranceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool HasCivilInsuranceSpecified {
            get {
                return this.hasCivilInsuranceFieldSpecified;
            }
            set {
                this.hasCivilInsuranceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool HasDamageInsurance {
            get {
                return this.hasDamageInsuranceField;
            }
            set {
                this.hasDamageInsuranceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool HasDamageInsuranceSpecified {
            get {
                return this.hasDamageInsuranceFieldSpecified;
            }
            set {
                this.hasDamageInsuranceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool HasVignette {
            get {
                return this.hasVignetteField;
            }
            set {
                this.hasVignetteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool HasVignetteSpecified {
            get {
                return this.hasVignetteFieldSpecified;
            }
            set {
                this.hasVignetteFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime RecentRegDate {
            get {
                return this.recentRegDateField;
            }
            set {
                this.recentRegDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RecentRegDateSpecified {
            get {
                return this.recentRegDateFieldSpecified;
            }
            set {
                this.recentRegDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string RegNum {
            get {
                return this.regNumField;
            }
            set {
                this.regNumField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime VignetteValidUntil {
            get {
                return this.vignetteValidUntilField;
            }
            set {
                this.vignetteValidUntilField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool VignetteValidUntilSpecified {
            get {
                return this.vignetteValidUntilFieldSpecified;
            }
            set {
                this.vignetteValidUntilFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/TrafficPoliceWcfHost.Model")]
    public partial class Penalty {
        
        private string descriptionField;
        
        private string disagreementField;
        
        private long driverOwnerIdField;
        
        private bool driverOwnerIdFieldSpecified;
        
        private System.DateTime happenedDateTimeField;
        
        private bool happenedDateTimeFieldSpecified;
        
        private System.DateTime issuedDateTimeField;
        
        private bool issuedDateTimeFieldSpecified;
        
        private long issuerIdField;
        
        private bool issuerIdFieldSpecified;
        
        private double latitudeField;
        
        private bool latitudeFieldSpecified;
        
        private string locationField;
        
        private double longtitudeField;
        
        private bool longtitudeFieldSpecified;
        
        private ulong penaltyIdField;
        
        private bool penaltyIdFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Disagreement {
            get {
                return this.disagreementField;
            }
            set {
                this.disagreementField = value;
            }
        }
        
        /// <remarks/>
        public long DriverOwnerId {
            get {
                return this.driverOwnerIdField;
            }
            set {
                this.driverOwnerIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DriverOwnerIdSpecified {
            get {
                return this.driverOwnerIdFieldSpecified;
            }
            set {
                this.driverOwnerIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime HappenedDateTime {
            get {
                return this.happenedDateTimeField;
            }
            set {
                this.happenedDateTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool HappenedDateTimeSpecified {
            get {
                return this.happenedDateTimeFieldSpecified;
            }
            set {
                this.happenedDateTimeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime IssuedDateTime {
            get {
                return this.issuedDateTimeField;
            }
            set {
                this.issuedDateTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IssuedDateTimeSpecified {
            get {
                return this.issuedDateTimeFieldSpecified;
            }
            set {
                this.issuedDateTimeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public long IssuerId {
            get {
                return this.issuerIdField;
            }
            set {
                this.issuerIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IssuerIdSpecified {
            get {
                return this.issuerIdFieldSpecified;
            }
            set {
                this.issuerIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double Latitude {
            get {
                return this.latitudeField;
            }
            set {
                this.latitudeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LatitudeSpecified {
            get {
                return this.latitudeFieldSpecified;
            }
            set {
                this.latitudeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
            }
        }
        
        /// <remarks/>
        public double Longtitude {
            get {
                return this.longtitudeField;
            }
            set {
                this.longtitudeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LongtitudeSpecified {
            get {
                return this.longtitudeFieldSpecified;
            }
            set {
                this.longtitudeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public ulong PenaltyId {
            get {
                return this.penaltyIdField;
            }
            set {
                this.penaltyIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PenaltyIdSpecified {
            get {
                return this.penaltyIdFieldSpecified;
            }
            set {
                this.penaltyIdFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/TrafficPoliceWcfHost.Model")]
    public partial class Categories {
        
        private System.DateTime a1AcquiryDateField;
        
        private bool a1AcquiryDateFieldSpecified;
        
        private System.DateTime a1ExpiryDateField;
        
        private bool a1ExpiryDateFieldSpecified;
        
        private string a1RestrictionsField;
        
        private System.DateTime aAcquiryDateField;
        
        private bool aAcquiryDateFieldSpecified;
        
        private System.DateTime aExpiryDateField;
        
        private bool aExpiryDateFieldSpecified;
        
        private string aRestrictionsField;
        
        private System.DateTime b1AcquiryDateField;
        
        private bool b1AcquiryDateFieldSpecified;
        
        private System.DateTime b1ExpiryDateField;
        
        private bool b1ExpiryDateFieldSpecified;
        
        private string b1RestrictionsField;
        
        private System.DateTime bAcquiryDateField;
        
        private bool bAcquiryDateFieldSpecified;
        
        private System.DateTime bExpiryDateField;
        
        private bool bExpiryDateFieldSpecified;
        
        private string bRestrictionsField;
        
        private System.DateTime beAcquiryDateField;
        
        private bool beAcquiryDateFieldSpecified;
        
        private System.DateTime beExpiryDateField;
        
        private bool beExpiryDateFieldSpecified;
        
        private string beRestrictionsField;
        
        private System.DateTime c1AcquiryDateField;
        
        private bool c1AcquiryDateFieldSpecified;
        
        private System.DateTime c1ExpiryDateField;
        
        private bool c1ExpiryDateFieldSpecified;
        
        private string c1RestrictionsField;
        
        private System.DateTime c1eAcquiryDateField;
        
        private bool c1eAcquiryDateFieldSpecified;
        
        private System.DateTime c1eExpiryDateField;
        
        private bool c1eExpiryDateFieldSpecified;
        
        private string c1eRestrictionsField;
        
        private System.DateTime cAcquiryDateField;
        
        private bool cAcquiryDateFieldSpecified;
        
        private System.DateTime cExpiryDateField;
        
        private bool cExpiryDateFieldSpecified;
        
        private string cRestrictionsField;
        
        private System.DateTime ceAcquiryDateField;
        
        private bool ceAcquiryDateFieldSpecified;
        
        private System.DateTime ceExpiryDateField;
        
        private bool ceExpiryDateFieldSpecified;
        
        private string ceRestrictionsField;
        
        private System.DateTime d1AcquiryDateField;
        
        private bool d1AcquiryDateFieldSpecified;
        
        private System.DateTime d1ExpiryDateField;
        
        private bool d1ExpiryDateFieldSpecified;
        
        private string d1RestrictionsField;
        
        private System.DateTime d1eAcquiryDateField;
        
        private bool d1eAcquiryDateFieldSpecified;
        
        private System.DateTime d1eExpiryDateField;
        
        private bool d1eExpiryDateFieldSpecified;
        
        private string d1eRestrictionsField;
        
        private System.DateTime dAcquiryDateField;
        
        private bool dAcquiryDateFieldSpecified;
        
        private System.DateTime dExpiryDateField;
        
        private bool dExpiryDateFieldSpecified;
        
        private string dRestrictionsField;
        
        private System.DateTime deAcquiryDateField;
        
        private bool deAcquiryDateFieldSpecified;
        
        private System.DateTime deExpiryDateField;
        
        private bool deExpiryDateFieldSpecified;
        
        private string deRestrictionsField;
        
        private System.DateTime mAcquiryDateField;
        
        private bool mAcquiryDateFieldSpecified;
        
        private System.DateTime mExpiryDateField;
        
        private bool mExpiryDateFieldSpecified;
        
        private string mRestrictionsField;
        
        private System.DateTime tktAcquiryDateField;
        
        private bool tktAcquiryDateFieldSpecified;
        
        private System.DateTime tktExpiryDateField;
        
        private bool tktExpiryDateFieldSpecified;
        
        private string tktRestrictionsField;
        
        private System.DateTime ttbAcquiryDateField;
        
        private bool ttbAcquiryDateFieldSpecified;
        
        private System.DateTime ttbExpiryDateField;
        
        private bool ttbExpiryDateFieldSpecified;
        
        private string ttbRestrictionsField;
        
        private System.DateTime ttmAcquiryDateField;
        
        private bool ttmAcquiryDateFieldSpecified;
        
        private System.DateTime ttmExpiryDateField;
        
        private bool ttmExpiryDateFieldSpecified;
        
        private string ttmRestrictionsField;
        
        /// <remarks/>
        public System.DateTime a1AcquiryDate {
            get {
                return this.a1AcquiryDateField;
            }
            set {
                this.a1AcquiryDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool a1AcquiryDateSpecified {
            get {
                return this.a1AcquiryDateFieldSpecified;
            }
            set {
                this.a1AcquiryDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime a1ExpiryDate {
            get {
                return this.a1ExpiryDateField;
            }
            set {
                this.a1ExpiryDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool a1ExpiryDateSpecified {
            get {
                return this.a1ExpiryDateFieldSpecified;
            }
            set {
                this.a1ExpiryDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string a1Restrictions {
            get {
                return this.a1RestrictionsField;
            }
            set {
                this.a1RestrictionsField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime aAcquiryDate {
            get {
                return this.aAcquiryDateField;
            }
            set {
                this.aAcquiryDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool aAcquiryDateSpecified {
            get {
                return this.aAcquiryDateFieldSpecified;
            }
            set {
                this.aAcquiryDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime aExpiryDate {
            get {
                return this.aExpiryDateField;
            }
            set {
                this.aExpiryDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool aExpiryDateSpecified {
            get {
                return this.aExpiryDateFieldSpecified;
            }
            set {
                this.aExpiryDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string aRestrictions {
            get {
                return this.aRestrictionsField;
            }
            set {
                this.aRestrictionsField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime b1AcquiryDate {
            get {
                return this.b1AcquiryDateField;
            }
            set {
                this.b1AcquiryDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool b1AcquiryDateSpecified {
            get {
                return this.b1AcquiryDateFieldSpecified;
            }
            set {
                this.b1AcquiryDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime b1ExpiryDate {
            get {
                return this.b1ExpiryDateField;
            }
            set {
                this.b1ExpiryDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool b1ExpiryDateSpecified {
            get {
                return this.b1ExpiryDateFieldSpecified;
            }
            set {
                this.b1ExpiryDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string b1Restrictions {
            get {
                return this.b1RestrictionsField;
            }
            set {
                this.b1RestrictionsField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime bAcquiryDate {
            get {
                return this.bAcquiryDateField;
            }
            set {
                this.bAcquiryDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool bAcquiryDateSpecified {
            get {
                return this.bAcquiryDateFieldSpecified;
            }
            set {
                this.bAcquiryDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime bExpiryDate {
            get {
                return this.bExpiryDateField;
            }
            set {
                this.bExpiryDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool bExpiryDateSpecified {
            get {
                return this.bExpiryDateFieldSpecified;
            }
            set {
                this.bExpiryDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string bRestrictions {
            get {
                return this.bRestrictionsField;
            }
            set {
                this.bRestrictionsField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime beAcquiryDate {
            get {
                return this.beAcquiryDateField;
            }
            set {
                this.beAcquiryDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool beAcquiryDateSpecified {
            get {
                return this.beAcquiryDateFieldSpecified;
            }
            set {
                this.beAcquiryDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime beExpiryDate {
            get {
                return this.beExpiryDateField;
            }
            set {
                this.beExpiryDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool beExpiryDateSpecified {
            get {
                return this.beExpiryDateFieldSpecified;
            }
            set {
                this.beExpiryDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string beRestrictions {
            get {
                return this.beRestrictionsField;
            }
            set {
                this.beRestrictionsField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime c1AcquiryDate {
            get {
                return this.c1AcquiryDateField;
            }
            set {
                this.c1AcquiryDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool c1AcquiryDateSpecified {
            get {
                return this.c1AcquiryDateFieldSpecified;
            }
            set {
                this.c1AcquiryDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime c1ExpiryDate {
            get {
                return this.c1ExpiryDateField;
            }
            set {
                this.c1ExpiryDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool c1ExpiryDateSpecified {
            get {
                return this.c1ExpiryDateFieldSpecified;
            }
            set {
                this.c1ExpiryDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string c1Restrictions {
            get {
                return this.c1RestrictionsField;
            }
            set {
                this.c1RestrictionsField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime c1eAcquiryDate {
            get {
                return this.c1eAcquiryDateField;
            }
            set {
                this.c1eAcquiryDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool c1eAcquiryDateSpecified {
            get {
                return this.c1eAcquiryDateFieldSpecified;
            }
            set {
                this.c1eAcquiryDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime c1eExpiryDate {
            get {
                return this.c1eExpiryDateField;
            }
            set {
                this.c1eExpiryDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool c1eExpiryDateSpecified {
            get {
                return this.c1eExpiryDateFieldSpecified;
            }
            set {
                this.c1eExpiryDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string c1eRestrictions {
            get {
                return this.c1eRestrictionsField;
            }
            set {
                this.c1eRestrictionsField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime cAcquiryDate {
            get {
                return this.cAcquiryDateField;
            }
            set {
                this.cAcquiryDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool cAcquiryDateSpecified {
            get {
                return this.cAcquiryDateFieldSpecified;
            }
            set {
                this.cAcquiryDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime cExpiryDate {
            get {
                return this.cExpiryDateField;
            }
            set {
                this.cExpiryDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool cExpiryDateSpecified {
            get {
                return this.cExpiryDateFieldSpecified;
            }
            set {
                this.cExpiryDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string cRestrictions {
            get {
                return this.cRestrictionsField;
            }
            set {
                this.cRestrictionsField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ceAcquiryDate {
            get {
                return this.ceAcquiryDateField;
            }
            set {
                this.ceAcquiryDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ceAcquiryDateSpecified {
            get {
                return this.ceAcquiryDateFieldSpecified;
            }
            set {
                this.ceAcquiryDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ceExpiryDate {
            get {
                return this.ceExpiryDateField;
            }
            set {
                this.ceExpiryDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ceExpiryDateSpecified {
            get {
                return this.ceExpiryDateFieldSpecified;
            }
            set {
                this.ceExpiryDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ceRestrictions {
            get {
                return this.ceRestrictionsField;
            }
            set {
                this.ceRestrictionsField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime d1AcquiryDate {
            get {
                return this.d1AcquiryDateField;
            }
            set {
                this.d1AcquiryDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool d1AcquiryDateSpecified {
            get {
                return this.d1AcquiryDateFieldSpecified;
            }
            set {
                this.d1AcquiryDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime d1ExpiryDate {
            get {
                return this.d1ExpiryDateField;
            }
            set {
                this.d1ExpiryDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool d1ExpiryDateSpecified {
            get {
                return this.d1ExpiryDateFieldSpecified;
            }
            set {
                this.d1ExpiryDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string d1Restrictions {
            get {
                return this.d1RestrictionsField;
            }
            set {
                this.d1RestrictionsField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime d1eAcquiryDate {
            get {
                return this.d1eAcquiryDateField;
            }
            set {
                this.d1eAcquiryDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool d1eAcquiryDateSpecified {
            get {
                return this.d1eAcquiryDateFieldSpecified;
            }
            set {
                this.d1eAcquiryDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime d1eExpiryDate {
            get {
                return this.d1eExpiryDateField;
            }
            set {
                this.d1eExpiryDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool d1eExpiryDateSpecified {
            get {
                return this.d1eExpiryDateFieldSpecified;
            }
            set {
                this.d1eExpiryDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string d1eRestrictions {
            get {
                return this.d1eRestrictionsField;
            }
            set {
                this.d1eRestrictionsField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime dAcquiryDate {
            get {
                return this.dAcquiryDateField;
            }
            set {
                this.dAcquiryDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dAcquiryDateSpecified {
            get {
                return this.dAcquiryDateFieldSpecified;
            }
            set {
                this.dAcquiryDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime dExpiryDate {
            get {
                return this.dExpiryDateField;
            }
            set {
                this.dExpiryDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dExpiryDateSpecified {
            get {
                return this.dExpiryDateFieldSpecified;
            }
            set {
                this.dExpiryDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string dRestrictions {
            get {
                return this.dRestrictionsField;
            }
            set {
                this.dRestrictionsField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime deAcquiryDate {
            get {
                return this.deAcquiryDateField;
            }
            set {
                this.deAcquiryDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool deAcquiryDateSpecified {
            get {
                return this.deAcquiryDateFieldSpecified;
            }
            set {
                this.deAcquiryDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime deExpiryDate {
            get {
                return this.deExpiryDateField;
            }
            set {
                this.deExpiryDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool deExpiryDateSpecified {
            get {
                return this.deExpiryDateFieldSpecified;
            }
            set {
                this.deExpiryDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string deRestrictions {
            get {
                return this.deRestrictionsField;
            }
            set {
                this.deRestrictionsField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime mAcquiryDate {
            get {
                return this.mAcquiryDateField;
            }
            set {
                this.mAcquiryDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool mAcquiryDateSpecified {
            get {
                return this.mAcquiryDateFieldSpecified;
            }
            set {
                this.mAcquiryDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime mExpiryDate {
            get {
                return this.mExpiryDateField;
            }
            set {
                this.mExpiryDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool mExpiryDateSpecified {
            get {
                return this.mExpiryDateFieldSpecified;
            }
            set {
                this.mExpiryDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string mRestrictions {
            get {
                return this.mRestrictionsField;
            }
            set {
                this.mRestrictionsField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime tktAcquiryDate {
            get {
                return this.tktAcquiryDateField;
            }
            set {
                this.tktAcquiryDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tktAcquiryDateSpecified {
            get {
                return this.tktAcquiryDateFieldSpecified;
            }
            set {
                this.tktAcquiryDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime tktExpiryDate {
            get {
                return this.tktExpiryDateField;
            }
            set {
                this.tktExpiryDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tktExpiryDateSpecified {
            get {
                return this.tktExpiryDateFieldSpecified;
            }
            set {
                this.tktExpiryDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string tktRestrictions {
            get {
                return this.tktRestrictionsField;
            }
            set {
                this.tktRestrictionsField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ttbAcquiryDate {
            get {
                return this.ttbAcquiryDateField;
            }
            set {
                this.ttbAcquiryDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ttbAcquiryDateSpecified {
            get {
                return this.ttbAcquiryDateFieldSpecified;
            }
            set {
                this.ttbAcquiryDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ttbExpiryDate {
            get {
                return this.ttbExpiryDateField;
            }
            set {
                this.ttbExpiryDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ttbExpiryDateSpecified {
            get {
                return this.ttbExpiryDateFieldSpecified;
            }
            set {
                this.ttbExpiryDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ttbRestrictions {
            get {
                return this.ttbRestrictionsField;
            }
            set {
                this.ttbRestrictionsField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ttmAcquiryDate {
            get {
                return this.ttmAcquiryDateField;
            }
            set {
                this.ttmAcquiryDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ttmAcquiryDateSpecified {
            get {
                return this.ttmAcquiryDateFieldSpecified;
            }
            set {
                this.ttmAcquiryDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ttmExpiryDate {
            get {
                return this.ttmExpiryDateField;
            }
            set {
                this.ttmExpiryDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ttmExpiryDateSpecified {
            get {
                return this.ttmExpiryDateFieldSpecified;
            }
            set {
                this.ttmExpiryDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ttmRestrictions {
            get {
                return this.ttmRestrictionsField;
            }
            set {
                this.ttmRestrictionsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/TrafficPoliceWcfHost.Model")]
    public partial class DriverOwner {
        
        private System.DateTime birthDateField;
        
        private bool birthDateFieldSpecified;
        
        private string birthPlaceField;
        
        private Categories categoriesField;
        
        private long driverOwnerIdField;
        
        private bool driverOwnerIdFieldSpecified;
        
        private string emailField;
        
        private string firstNameField;
        
        private string lastNameField;
        
        private System.DateTime licenceExpiryDateField;
        
        private bool licenceExpiryDateFieldSpecified;
        
        private System.DateTime licenceIssueDateField;
        
        private bool licenceIssueDateFieldSpecified;
        
        private string licenceIssuedByField;
        
        private string nationalityField;
        
        private Penalty[] penaltiesField;
        
        private int remainingPtsField;
        
        private bool remainingPtsFieldSpecified;
        
        private string residenceField;
        
        private string secondNameField;
        
        private Sex sexField;
        
        private bool sexFieldSpecified;
        
        private string telNumField;
        
        /// <remarks/>
        public System.DateTime BirthDate {
            get {
                return this.birthDateField;
            }
            set {
                this.birthDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BirthDateSpecified {
            get {
                return this.birthDateFieldSpecified;
            }
            set {
                this.birthDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string BirthPlace {
            get {
                return this.birthPlaceField;
            }
            set {
                this.birthPlaceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Categories Categories {
            get {
                return this.categoriesField;
            }
            set {
                this.categoriesField = value;
            }
        }
        
        /// <remarks/>
        public long DriverOwnerId {
            get {
                return this.driverOwnerIdField;
            }
            set {
                this.driverOwnerIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DriverOwnerIdSpecified {
            get {
                return this.driverOwnerIdFieldSpecified;
            }
            set {
                this.driverOwnerIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime LicenceExpiryDate {
            get {
                return this.licenceExpiryDateField;
            }
            set {
                this.licenceExpiryDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LicenceExpiryDateSpecified {
            get {
                return this.licenceExpiryDateFieldSpecified;
            }
            set {
                this.licenceExpiryDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime LicenceIssueDate {
            get {
                return this.licenceIssueDateField;
            }
            set {
                this.licenceIssueDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LicenceIssueDateSpecified {
            get {
                return this.licenceIssueDateFieldSpecified;
            }
            set {
                this.licenceIssueDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string LicenceIssuedBy {
            get {
                return this.licenceIssuedByField;
            }
            set {
                this.licenceIssuedByField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Nationality {
            get {
                return this.nationalityField;
            }
            set {
                this.nationalityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public Penalty[] Penalties {
            get {
                return this.penaltiesField;
            }
            set {
                this.penaltiesField = value;
            }
        }
        
        /// <remarks/>
        public int RemainingPts {
            get {
                return this.remainingPtsField;
            }
            set {
                this.remainingPtsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RemainingPtsSpecified {
            get {
                return this.remainingPtsFieldSpecified;
            }
            set {
                this.remainingPtsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Residence {
            get {
                return this.residenceField;
            }
            set {
                this.residenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string SecondName {
            get {
                return this.secondNameField;
            }
            set {
                this.secondNameField = value;
            }
        }
        
        /// <remarks/>
        public Sex Sex {
            get {
                return this.sexField;
            }
            set {
                this.sexField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SexSpecified {
            get {
                return this.sexFieldSpecified;
            }
            set {
                this.sexFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string TelNum {
            get {
                return this.telNumField;
            }
            set {
                this.telNumField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.FlagsAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/TrafficPoliceWcfHost.Model")]
    public enum Sex {
        
        /// <remarks/>
        Man = 1,
        
        /// <remarks/>
        Woman = 2,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void GetUserByIdAndPassCompletedEventHandler(object sender, GetUserByIdAndPassCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUserByIdAndPassCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUserByIdAndPassCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public User Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((User)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void GetDriverOwnerByIdCompletedEventHandler(object sender, GetDriverOwnerByIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDriverOwnerByIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDriverOwnerByIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DriverOwner Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DriverOwner)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void getRegByRegNumCompletedEventHandler(object sender, getRegByRegNumCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getRegByRegNumCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getRegByRegNumCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Registration Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Registration)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void addPenaltyToDriverOwnerCompletedEventHandler(object sender, addPenaltyToDriverOwnerCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class addPenaltyToDriverOwnerCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal addPenaltyToDriverOwnerCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591