//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrafficPolice.Core.TrafficPoliceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/TrafficPoliceWcfHost.Model")]
    public partial class User : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string FirstNameField;
        
        private bool IsTrafficPolicemanField;
        
        private string LastNameField;
        
        private string SecondNameField;
        
        private long UserIdField;
        
        private string UserPasswordField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsTrafficPoliceman {
            get {
                return this.IsTrafficPolicemanField;
            }
            set {
                if ((this.IsTrafficPolicemanField.Equals(value) != true)) {
                    this.IsTrafficPolicemanField = value;
                    this.RaisePropertyChanged("IsTrafficPoliceman");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SecondName {
            get {
                return this.SecondNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SecondNameField, value) != true)) {
                    this.SecondNameField = value;
                    this.RaisePropertyChanged("SecondName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserPassword {
            get {
                return this.UserPasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.UserPasswordField, value) != true)) {
                    this.UserPasswordField = value;
                    this.RaisePropertyChanged("UserPassword");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DriverOwner", Namespace="http://schemas.datacontract.org/2004/07/TrafficPoliceWcfHost.Model")]
    public partial class DriverOwner : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime BirthDateField;
        
        private string BirthPlaceField;
        
        private TrafficPolice.Core.TrafficPoliceReference.Categories CategoriesField;
        
        private long DriverOwnerIdField;
        
        private string EmailField;
        
        private string FirstNameField;
        
        private string LastNameField;
        
        private System.DateTime LicenceExpiryDateField;
        
        private System.DateTime LicenceIssueDateField;
        
        private string LicenceIssuedByField;
        
        private string NationalityField;
        
        private System.Collections.ObjectModel.ObservableCollection<TrafficPolice.Core.TrafficPoliceReference.Penalty> PenaltiesField;
        
        private int RemainingPtsField;
        
        private string ResidenceField;
        
        private string SecondNameField;
        
        private TrafficPolice.Core.TrafficPoliceReference.Sex SexField;
        
        private string TelNumField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime BirthDate {
            get {
                return this.BirthDateField;
            }
            set {
                if ((this.BirthDateField.Equals(value) != true)) {
                    this.BirthDateField = value;
                    this.RaisePropertyChanged("BirthDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BirthPlace {
            get {
                return this.BirthPlaceField;
            }
            set {
                if ((object.ReferenceEquals(this.BirthPlaceField, value) != true)) {
                    this.BirthPlaceField = value;
                    this.RaisePropertyChanged("BirthPlace");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TrafficPolice.Core.TrafficPoliceReference.Categories Categories {
            get {
                return this.CategoriesField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoriesField, value) != true)) {
                    this.CategoriesField = value;
                    this.RaisePropertyChanged("Categories");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long DriverOwnerId {
            get {
                return this.DriverOwnerIdField;
            }
            set {
                if ((this.DriverOwnerIdField.Equals(value) != true)) {
                    this.DriverOwnerIdField = value;
                    this.RaisePropertyChanged("DriverOwnerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LicenceExpiryDate {
            get {
                return this.LicenceExpiryDateField;
            }
            set {
                if ((this.LicenceExpiryDateField.Equals(value) != true)) {
                    this.LicenceExpiryDateField = value;
                    this.RaisePropertyChanged("LicenceExpiryDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LicenceIssueDate {
            get {
                return this.LicenceIssueDateField;
            }
            set {
                if ((this.LicenceIssueDateField.Equals(value) != true)) {
                    this.LicenceIssueDateField = value;
                    this.RaisePropertyChanged("LicenceIssueDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LicenceIssuedBy {
            get {
                return this.LicenceIssuedByField;
            }
            set {
                if ((object.ReferenceEquals(this.LicenceIssuedByField, value) != true)) {
                    this.LicenceIssuedByField = value;
                    this.RaisePropertyChanged("LicenceIssuedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nationality {
            get {
                return this.NationalityField;
            }
            set {
                if ((object.ReferenceEquals(this.NationalityField, value) != true)) {
                    this.NationalityField = value;
                    this.RaisePropertyChanged("Nationality");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<TrafficPolice.Core.TrafficPoliceReference.Penalty> Penalties {
            get {
                return this.PenaltiesField;
            }
            set {
                if ((object.ReferenceEquals(this.PenaltiesField, value) != true)) {
                    this.PenaltiesField = value;
                    this.RaisePropertyChanged("Penalties");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RemainingPts {
            get {
                return this.RemainingPtsField;
            }
            set {
                if ((this.RemainingPtsField.Equals(value) != true)) {
                    this.RemainingPtsField = value;
                    this.RaisePropertyChanged("RemainingPts");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Residence {
            get {
                return this.ResidenceField;
            }
            set {
                if ((object.ReferenceEquals(this.ResidenceField, value) != true)) {
                    this.ResidenceField = value;
                    this.RaisePropertyChanged("Residence");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SecondName {
            get {
                return this.SecondNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SecondNameField, value) != true)) {
                    this.SecondNameField = value;
                    this.RaisePropertyChanged("SecondName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TrafficPolice.Core.TrafficPoliceReference.Sex Sex {
            get {
                return this.SexField;
            }
            set {
                if ((this.SexField.Equals(value) != true)) {
                    this.SexField = value;
                    this.RaisePropertyChanged("Sex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TelNum {
            get {
                return this.TelNumField;
            }
            set {
                if ((object.ReferenceEquals(this.TelNumField, value) != true)) {
                    this.TelNumField = value;
                    this.RaisePropertyChanged("TelNum");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Categories", Namespace="http://schemas.datacontract.org/2004/07/TrafficPoliceWcfHost.Model")]
    public partial class Categories : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime a1AcquiryDateField;
        
        private System.DateTime a1ExpiryDateField;
        
        private string a1RestrictionsField;
        
        private System.DateTime aAcquiryDateField;
        
        private System.DateTime aExpiryDateField;
        
        private string aRestrictionsField;
        
        private System.DateTime b1AcquiryDateField;
        
        private System.DateTime b1ExpiryDateField;
        
        private string b1RestrictionsField;
        
        private System.DateTime bAcquiryDateField;
        
        private System.DateTime bExpiryDateField;
        
        private string bRestrictionsField;
        
        private System.DateTime beAcquiryDateField;
        
        private System.DateTime beExpiryDateField;
        
        private string beRestrictionsField;
        
        private System.DateTime c1AcquiryDateField;
        
        private System.DateTime c1ExpiryDateField;
        
        private string c1RestrictionsField;
        
        private System.DateTime c1eAcquiryDateField;
        
        private System.DateTime c1eExpiryDateField;
        
        private string c1eRestrictionsField;
        
        private System.DateTime cAcquiryDateField;
        
        private System.DateTime cExpiryDateField;
        
        private string cRestrictionsField;
        
        private System.DateTime ceAcquiryDateField;
        
        private System.DateTime ceExpiryDateField;
        
        private string ceRestrictionsField;
        
        private System.DateTime d1AcquiryDateField;
        
        private System.DateTime d1ExpiryDateField;
        
        private string d1RestrictionsField;
        
        private System.DateTime d1eAcquiryDateField;
        
        private System.DateTime d1eExpiryDateField;
        
        private string d1eRestrictionsField;
        
        private System.DateTime dAcquiryDateField;
        
        private System.DateTime dExpiryDateField;
        
        private string dRestrictionsField;
        
        private System.DateTime deAcquiryDateField;
        
        private System.DateTime deExpiryDateField;
        
        private string deRestrictionsField;
        
        private System.DateTime mAcquiryDateField;
        
        private System.DateTime mExpiryDateField;
        
        private string mRestrictionsField;
        
        private System.DateTime tktAcquiryDateField;
        
        private System.DateTime tktExpiryDateField;
        
        private string tktRestrictionsField;
        
        private System.DateTime ttbAcquiryDateField;
        
        private System.DateTime ttbExpiryDateField;
        
        private string ttbRestrictionsField;
        
        private System.DateTime ttmAcquiryDateField;
        
        private System.DateTime ttmExpiryDateField;
        
        private string ttmRestrictionsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime a1AcquiryDate {
            get {
                return this.a1AcquiryDateField;
            }
            set {
                if ((this.a1AcquiryDateField.Equals(value) != true)) {
                    this.a1AcquiryDateField = value;
                    this.RaisePropertyChanged("a1AcquiryDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime a1ExpiryDate {
            get {
                return this.a1ExpiryDateField;
            }
            set {
                if ((this.a1ExpiryDateField.Equals(value) != true)) {
                    this.a1ExpiryDateField = value;
                    this.RaisePropertyChanged("a1ExpiryDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string a1Restrictions {
            get {
                return this.a1RestrictionsField;
            }
            set {
                if ((object.ReferenceEquals(this.a1RestrictionsField, value) != true)) {
                    this.a1RestrictionsField = value;
                    this.RaisePropertyChanged("a1Restrictions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime aAcquiryDate {
            get {
                return this.aAcquiryDateField;
            }
            set {
                if ((this.aAcquiryDateField.Equals(value) != true)) {
                    this.aAcquiryDateField = value;
                    this.RaisePropertyChanged("aAcquiryDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime aExpiryDate {
            get {
                return this.aExpiryDateField;
            }
            set {
                if ((this.aExpiryDateField.Equals(value) != true)) {
                    this.aExpiryDateField = value;
                    this.RaisePropertyChanged("aExpiryDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string aRestrictions {
            get {
                return this.aRestrictionsField;
            }
            set {
                if ((object.ReferenceEquals(this.aRestrictionsField, value) != true)) {
                    this.aRestrictionsField = value;
                    this.RaisePropertyChanged("aRestrictions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime b1AcquiryDate {
            get {
                return this.b1AcquiryDateField;
            }
            set {
                if ((this.b1AcquiryDateField.Equals(value) != true)) {
                    this.b1AcquiryDateField = value;
                    this.RaisePropertyChanged("b1AcquiryDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime b1ExpiryDate {
            get {
                return this.b1ExpiryDateField;
            }
            set {
                if ((this.b1ExpiryDateField.Equals(value) != true)) {
                    this.b1ExpiryDateField = value;
                    this.RaisePropertyChanged("b1ExpiryDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string b1Restrictions {
            get {
                return this.b1RestrictionsField;
            }
            set {
                if ((object.ReferenceEquals(this.b1RestrictionsField, value) != true)) {
                    this.b1RestrictionsField = value;
                    this.RaisePropertyChanged("b1Restrictions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime bAcquiryDate {
            get {
                return this.bAcquiryDateField;
            }
            set {
                if ((this.bAcquiryDateField.Equals(value) != true)) {
                    this.bAcquiryDateField = value;
                    this.RaisePropertyChanged("bAcquiryDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime bExpiryDate {
            get {
                return this.bExpiryDateField;
            }
            set {
                if ((this.bExpiryDateField.Equals(value) != true)) {
                    this.bExpiryDateField = value;
                    this.RaisePropertyChanged("bExpiryDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string bRestrictions {
            get {
                return this.bRestrictionsField;
            }
            set {
                if ((object.ReferenceEquals(this.bRestrictionsField, value) != true)) {
                    this.bRestrictionsField = value;
                    this.RaisePropertyChanged("bRestrictions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime beAcquiryDate {
            get {
                return this.beAcquiryDateField;
            }
            set {
                if ((this.beAcquiryDateField.Equals(value) != true)) {
                    this.beAcquiryDateField = value;
                    this.RaisePropertyChanged("beAcquiryDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime beExpiryDate {
            get {
                return this.beExpiryDateField;
            }
            set {
                if ((this.beExpiryDateField.Equals(value) != true)) {
                    this.beExpiryDateField = value;
                    this.RaisePropertyChanged("beExpiryDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string beRestrictions {
            get {
                return this.beRestrictionsField;
            }
            set {
                if ((object.ReferenceEquals(this.beRestrictionsField, value) != true)) {
                    this.beRestrictionsField = value;
                    this.RaisePropertyChanged("beRestrictions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime c1AcquiryDate {
            get {
                return this.c1AcquiryDateField;
            }
            set {
                if ((this.c1AcquiryDateField.Equals(value) != true)) {
                    this.c1AcquiryDateField = value;
                    this.RaisePropertyChanged("c1AcquiryDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime c1ExpiryDate {
            get {
                return this.c1ExpiryDateField;
            }
            set {
                if ((this.c1ExpiryDateField.Equals(value) != true)) {
                    this.c1ExpiryDateField = value;
                    this.RaisePropertyChanged("c1ExpiryDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string c1Restrictions {
            get {
                return this.c1RestrictionsField;
            }
            set {
                if ((object.ReferenceEquals(this.c1RestrictionsField, value) != true)) {
                    this.c1RestrictionsField = value;
                    this.RaisePropertyChanged("c1Restrictions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime c1eAcquiryDate {
            get {
                return this.c1eAcquiryDateField;
            }
            set {
                if ((this.c1eAcquiryDateField.Equals(value) != true)) {
                    this.c1eAcquiryDateField = value;
                    this.RaisePropertyChanged("c1eAcquiryDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime c1eExpiryDate {
            get {
                return this.c1eExpiryDateField;
            }
            set {
                if ((this.c1eExpiryDateField.Equals(value) != true)) {
                    this.c1eExpiryDateField = value;
                    this.RaisePropertyChanged("c1eExpiryDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string c1eRestrictions {
            get {
                return this.c1eRestrictionsField;
            }
            set {
                if ((object.ReferenceEquals(this.c1eRestrictionsField, value) != true)) {
                    this.c1eRestrictionsField = value;
                    this.RaisePropertyChanged("c1eRestrictions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime cAcquiryDate {
            get {
                return this.cAcquiryDateField;
            }
            set {
                if ((this.cAcquiryDateField.Equals(value) != true)) {
                    this.cAcquiryDateField = value;
                    this.RaisePropertyChanged("cAcquiryDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime cExpiryDate {
            get {
                return this.cExpiryDateField;
            }
            set {
                if ((this.cExpiryDateField.Equals(value) != true)) {
                    this.cExpiryDateField = value;
                    this.RaisePropertyChanged("cExpiryDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cRestrictions {
            get {
                return this.cRestrictionsField;
            }
            set {
                if ((object.ReferenceEquals(this.cRestrictionsField, value) != true)) {
                    this.cRestrictionsField = value;
                    this.RaisePropertyChanged("cRestrictions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ceAcquiryDate {
            get {
                return this.ceAcquiryDateField;
            }
            set {
                if ((this.ceAcquiryDateField.Equals(value) != true)) {
                    this.ceAcquiryDateField = value;
                    this.RaisePropertyChanged("ceAcquiryDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ceExpiryDate {
            get {
                return this.ceExpiryDateField;
            }
            set {
                if ((this.ceExpiryDateField.Equals(value) != true)) {
                    this.ceExpiryDateField = value;
                    this.RaisePropertyChanged("ceExpiryDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ceRestrictions {
            get {
                return this.ceRestrictionsField;
            }
            set {
                if ((object.ReferenceEquals(this.ceRestrictionsField, value) != true)) {
                    this.ceRestrictionsField = value;
                    this.RaisePropertyChanged("ceRestrictions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime d1AcquiryDate {
            get {
                return this.d1AcquiryDateField;
            }
            set {
                if ((this.d1AcquiryDateField.Equals(value) != true)) {
                    this.d1AcquiryDateField = value;
                    this.RaisePropertyChanged("d1AcquiryDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime d1ExpiryDate {
            get {
                return this.d1ExpiryDateField;
            }
            set {
                if ((this.d1ExpiryDateField.Equals(value) != true)) {
                    this.d1ExpiryDateField = value;
                    this.RaisePropertyChanged("d1ExpiryDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string d1Restrictions {
            get {
                return this.d1RestrictionsField;
            }
            set {
                if ((object.ReferenceEquals(this.d1RestrictionsField, value) != true)) {
                    this.d1RestrictionsField = value;
                    this.RaisePropertyChanged("d1Restrictions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime d1eAcquiryDate {
            get {
                return this.d1eAcquiryDateField;
            }
            set {
                if ((this.d1eAcquiryDateField.Equals(value) != true)) {
                    this.d1eAcquiryDateField = value;
                    this.RaisePropertyChanged("d1eAcquiryDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime d1eExpiryDate {
            get {
                return this.d1eExpiryDateField;
            }
            set {
                if ((this.d1eExpiryDateField.Equals(value) != true)) {
                    this.d1eExpiryDateField = value;
                    this.RaisePropertyChanged("d1eExpiryDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string d1eRestrictions {
            get {
                return this.d1eRestrictionsField;
            }
            set {
                if ((object.ReferenceEquals(this.d1eRestrictionsField, value) != true)) {
                    this.d1eRestrictionsField = value;
                    this.RaisePropertyChanged("d1eRestrictions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime dAcquiryDate {
            get {
                return this.dAcquiryDateField;
            }
            set {
                if ((this.dAcquiryDateField.Equals(value) != true)) {
                    this.dAcquiryDateField = value;
                    this.RaisePropertyChanged("dAcquiryDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime dExpiryDate {
            get {
                return this.dExpiryDateField;
            }
            set {
                if ((this.dExpiryDateField.Equals(value) != true)) {
                    this.dExpiryDateField = value;
                    this.RaisePropertyChanged("dExpiryDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string dRestrictions {
            get {
                return this.dRestrictionsField;
            }
            set {
                if ((object.ReferenceEquals(this.dRestrictionsField, value) != true)) {
                    this.dRestrictionsField = value;
                    this.RaisePropertyChanged("dRestrictions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime deAcquiryDate {
            get {
                return this.deAcquiryDateField;
            }
            set {
                if ((this.deAcquiryDateField.Equals(value) != true)) {
                    this.deAcquiryDateField = value;
                    this.RaisePropertyChanged("deAcquiryDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime deExpiryDate {
            get {
                return this.deExpiryDateField;
            }
            set {
                if ((this.deExpiryDateField.Equals(value) != true)) {
                    this.deExpiryDateField = value;
                    this.RaisePropertyChanged("deExpiryDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string deRestrictions {
            get {
                return this.deRestrictionsField;
            }
            set {
                if ((object.ReferenceEquals(this.deRestrictionsField, value) != true)) {
                    this.deRestrictionsField = value;
                    this.RaisePropertyChanged("deRestrictions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime mAcquiryDate {
            get {
                return this.mAcquiryDateField;
            }
            set {
                if ((this.mAcquiryDateField.Equals(value) != true)) {
                    this.mAcquiryDateField = value;
                    this.RaisePropertyChanged("mAcquiryDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime mExpiryDate {
            get {
                return this.mExpiryDateField;
            }
            set {
                if ((this.mExpiryDateField.Equals(value) != true)) {
                    this.mExpiryDateField = value;
                    this.RaisePropertyChanged("mExpiryDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string mRestrictions {
            get {
                return this.mRestrictionsField;
            }
            set {
                if ((object.ReferenceEquals(this.mRestrictionsField, value) != true)) {
                    this.mRestrictionsField = value;
                    this.RaisePropertyChanged("mRestrictions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime tktAcquiryDate {
            get {
                return this.tktAcquiryDateField;
            }
            set {
                if ((this.tktAcquiryDateField.Equals(value) != true)) {
                    this.tktAcquiryDateField = value;
                    this.RaisePropertyChanged("tktAcquiryDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime tktExpiryDate {
            get {
                return this.tktExpiryDateField;
            }
            set {
                if ((this.tktExpiryDateField.Equals(value) != true)) {
                    this.tktExpiryDateField = value;
                    this.RaisePropertyChanged("tktExpiryDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tktRestrictions {
            get {
                return this.tktRestrictionsField;
            }
            set {
                if ((object.ReferenceEquals(this.tktRestrictionsField, value) != true)) {
                    this.tktRestrictionsField = value;
                    this.RaisePropertyChanged("tktRestrictions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ttbAcquiryDate {
            get {
                return this.ttbAcquiryDateField;
            }
            set {
                if ((this.ttbAcquiryDateField.Equals(value) != true)) {
                    this.ttbAcquiryDateField = value;
                    this.RaisePropertyChanged("ttbAcquiryDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ttbExpiryDate {
            get {
                return this.ttbExpiryDateField;
            }
            set {
                if ((this.ttbExpiryDateField.Equals(value) != true)) {
                    this.ttbExpiryDateField = value;
                    this.RaisePropertyChanged("ttbExpiryDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ttbRestrictions {
            get {
                return this.ttbRestrictionsField;
            }
            set {
                if ((object.ReferenceEquals(this.ttbRestrictionsField, value) != true)) {
                    this.ttbRestrictionsField = value;
                    this.RaisePropertyChanged("ttbRestrictions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ttmAcquiryDate {
            get {
                return this.ttmAcquiryDateField;
            }
            set {
                if ((this.ttmAcquiryDateField.Equals(value) != true)) {
                    this.ttmAcquiryDateField = value;
                    this.RaisePropertyChanged("ttmAcquiryDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ttmExpiryDate {
            get {
                return this.ttmExpiryDateField;
            }
            set {
                if ((this.ttmExpiryDateField.Equals(value) != true)) {
                    this.ttmExpiryDateField = value;
                    this.RaisePropertyChanged("ttmExpiryDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ttmRestrictions {
            get {
                return this.ttmRestrictionsField;
            }
            set {
                if ((object.ReferenceEquals(this.ttmRestrictionsField, value) != true)) {
                    this.ttmRestrictionsField = value;
                    this.RaisePropertyChanged("ttmRestrictions");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Penalty", Namespace="http://schemas.datacontract.org/2004/07/TrafficPoliceWcfHost.Model")]
    public partial class Penalty : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string DescriptionField;
        
        private string DisagreementField;
        
        private long DriverOwnerIdField;
        
        private System.DateTime HappenedDateTimeField;
        
        private System.DateTime IssuedDateTimeField;
        
        private long IssuerIdField;
        
        private double LatitudeField;
        
        private string LocationField;
        
        private double LongtitudeField;
        
        private ulong PenaltyIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Disagreement {
            get {
                return this.DisagreementField;
            }
            set {
                if ((object.ReferenceEquals(this.DisagreementField, value) != true)) {
                    this.DisagreementField = value;
                    this.RaisePropertyChanged("Disagreement");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long DriverOwnerId {
            get {
                return this.DriverOwnerIdField;
            }
            set {
                if ((this.DriverOwnerIdField.Equals(value) != true)) {
                    this.DriverOwnerIdField = value;
                    this.RaisePropertyChanged("DriverOwnerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime HappenedDateTime {
            get {
                return this.HappenedDateTimeField;
            }
            set {
                if ((this.HappenedDateTimeField.Equals(value) != true)) {
                    this.HappenedDateTimeField = value;
                    this.RaisePropertyChanged("HappenedDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime IssuedDateTime {
            get {
                return this.IssuedDateTimeField;
            }
            set {
                if ((this.IssuedDateTimeField.Equals(value) != true)) {
                    this.IssuedDateTimeField = value;
                    this.RaisePropertyChanged("IssuedDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long IssuerId {
            get {
                return this.IssuerIdField;
            }
            set {
                if ((this.IssuerIdField.Equals(value) != true)) {
                    this.IssuerIdField = value;
                    this.RaisePropertyChanged("IssuerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Latitude {
            get {
                return this.LatitudeField;
            }
            set {
                if ((this.LatitudeField.Equals(value) != true)) {
                    this.LatitudeField = value;
                    this.RaisePropertyChanged("Latitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Location {
            get {
                return this.LocationField;
            }
            set {
                if ((object.ReferenceEquals(this.LocationField, value) != true)) {
                    this.LocationField = value;
                    this.RaisePropertyChanged("Location");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Longtitude {
            get {
                return this.LongtitudeField;
            }
            set {
                if ((this.LongtitudeField.Equals(value) != true)) {
                    this.LongtitudeField = value;
                    this.RaisePropertyChanged("Longtitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ulong PenaltyId {
            get {
                return this.PenaltyIdField;
            }
            set {
                if ((this.PenaltyIdField.Equals(value) != true)) {
                    this.PenaltyIdField = value;
                    this.RaisePropertyChanged("PenaltyId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.FlagsAttribute()]
    [System.Runtime.Serialization.DataContractAttribute(Name="Sex", Namespace="http://schemas.datacontract.org/2004/07/TrafficPoliceWcfHost.Model")]
    public enum Sex : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Man = 1052,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Woman = 1046,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Registration", Namespace="http://schemas.datacontract.org/2004/07/TrafficPoliceWcfHost.Model")]
    public partial class Registration : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string CarColorField;
        
        private int CarCubageField;
        
        private int CarHpField;
        
        private string CarManufacturerField;
        
        private string CarModelField;
        
        private string CarTypeField;
        
        private string CarVinField;
        
        private System.DateTime CivilInsuranceEndDateField;
        
        private System.DateTime CivilInsuranceStartDateField;
        
        private string CivilInsurerField;
        
        private System.DateTime DamageInsuranceEndDateField;
        
        private System.DateTime DamageInsuranceStartDateField;
        
        private string DamageInsurerField;
        
        private long DriverOwnerIdField;
        
        private System.DateTime FirstRegDateField;
        
        private bool HasCivilInsuranceField;
        
        private bool HasDamageInsuranceField;
        
        private bool HasVignetteField;
        
        private System.DateTime RecentRegDateField;
        
        private string RegNumField;
        
        private System.DateTime VignetteValidUntilField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CarColor {
            get {
                return this.CarColorField;
            }
            set {
                if ((object.ReferenceEquals(this.CarColorField, value) != true)) {
                    this.CarColorField = value;
                    this.RaisePropertyChanged("CarColor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CarCubage {
            get {
                return this.CarCubageField;
            }
            set {
                if ((this.CarCubageField.Equals(value) != true)) {
                    this.CarCubageField = value;
                    this.RaisePropertyChanged("CarCubage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CarHp {
            get {
                return this.CarHpField;
            }
            set {
                if ((this.CarHpField.Equals(value) != true)) {
                    this.CarHpField = value;
                    this.RaisePropertyChanged("CarHp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CarManufacturer {
            get {
                return this.CarManufacturerField;
            }
            set {
                if ((object.ReferenceEquals(this.CarManufacturerField, value) != true)) {
                    this.CarManufacturerField = value;
                    this.RaisePropertyChanged("CarManufacturer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CarModel {
            get {
                return this.CarModelField;
            }
            set {
                if ((object.ReferenceEquals(this.CarModelField, value) != true)) {
                    this.CarModelField = value;
                    this.RaisePropertyChanged("CarModel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CarType {
            get {
                return this.CarTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.CarTypeField, value) != true)) {
                    this.CarTypeField = value;
                    this.RaisePropertyChanged("CarType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CarVin {
            get {
                return this.CarVinField;
            }
            set {
                if ((object.ReferenceEquals(this.CarVinField, value) != true)) {
                    this.CarVinField = value;
                    this.RaisePropertyChanged("CarVin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CivilInsuranceEndDate {
            get {
                return this.CivilInsuranceEndDateField;
            }
            set {
                if ((this.CivilInsuranceEndDateField.Equals(value) != true)) {
                    this.CivilInsuranceEndDateField = value;
                    this.RaisePropertyChanged("CivilInsuranceEndDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CivilInsuranceStartDate {
            get {
                return this.CivilInsuranceStartDateField;
            }
            set {
                if ((this.CivilInsuranceStartDateField.Equals(value) != true)) {
                    this.CivilInsuranceStartDateField = value;
                    this.RaisePropertyChanged("CivilInsuranceStartDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CivilInsurer {
            get {
                return this.CivilInsurerField;
            }
            set {
                if ((object.ReferenceEquals(this.CivilInsurerField, value) != true)) {
                    this.CivilInsurerField = value;
                    this.RaisePropertyChanged("CivilInsurer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DamageInsuranceEndDate {
            get {
                return this.DamageInsuranceEndDateField;
            }
            set {
                if ((this.DamageInsuranceEndDateField.Equals(value) != true)) {
                    this.DamageInsuranceEndDateField = value;
                    this.RaisePropertyChanged("DamageInsuranceEndDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DamageInsuranceStartDate {
            get {
                return this.DamageInsuranceStartDateField;
            }
            set {
                if ((this.DamageInsuranceStartDateField.Equals(value) != true)) {
                    this.DamageInsuranceStartDateField = value;
                    this.RaisePropertyChanged("DamageInsuranceStartDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DamageInsurer {
            get {
                return this.DamageInsurerField;
            }
            set {
                if ((object.ReferenceEquals(this.DamageInsurerField, value) != true)) {
                    this.DamageInsurerField = value;
                    this.RaisePropertyChanged("DamageInsurer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long DriverOwnerId {
            get {
                return this.DriverOwnerIdField;
            }
            set {
                if ((this.DriverOwnerIdField.Equals(value) != true)) {
                    this.DriverOwnerIdField = value;
                    this.RaisePropertyChanged("DriverOwnerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FirstRegDate {
            get {
                return this.FirstRegDateField;
            }
            set {
                if ((this.FirstRegDateField.Equals(value) != true)) {
                    this.FirstRegDateField = value;
                    this.RaisePropertyChanged("FirstRegDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HasCivilInsurance {
            get {
                return this.HasCivilInsuranceField;
            }
            set {
                if ((this.HasCivilInsuranceField.Equals(value) != true)) {
                    this.HasCivilInsuranceField = value;
                    this.RaisePropertyChanged("HasCivilInsurance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HasDamageInsurance {
            get {
                return this.HasDamageInsuranceField;
            }
            set {
                if ((this.HasDamageInsuranceField.Equals(value) != true)) {
                    this.HasDamageInsuranceField = value;
                    this.RaisePropertyChanged("HasDamageInsurance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HasVignette {
            get {
                return this.HasVignetteField;
            }
            set {
                if ((this.HasVignetteField.Equals(value) != true)) {
                    this.HasVignetteField = value;
                    this.RaisePropertyChanged("HasVignette");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime RecentRegDate {
            get {
                return this.RecentRegDateField;
            }
            set {
                if ((this.RecentRegDateField.Equals(value) != true)) {
                    this.RecentRegDateField = value;
                    this.RaisePropertyChanged("RecentRegDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RegNum {
            get {
                return this.RegNumField;
            }
            set {
                if ((object.ReferenceEquals(this.RegNumField, value) != true)) {
                    this.RegNumField = value;
                    this.RaisePropertyChanged("RegNum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime VignetteValidUntil {
            get {
                return this.VignetteValidUntilField;
            }
            set {
                if ((this.VignetteValidUntilField.Equals(value) != true)) {
                    this.VignetteValidUntilField = value;
                    this.RaisePropertyChanged("VignetteValidUntil");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TrafficPoliceReference.ITrafficPoliceService")]
    public interface ITrafficPoliceService {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ITrafficPoliceService/GetUserByIdAndPass", ReplyAction="http://tempuri.org/ITrafficPoliceService/GetUserByIdAndPassResponse")]
        System.IAsyncResult BeginGetUserByIdAndPass(string id, string password, System.AsyncCallback callback, object asyncState);
        
        TrafficPolice.Core.TrafficPoliceReference.User EndGetUserByIdAndPass(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ITrafficPoliceService/GetDriverOwnerById", ReplyAction="http://tempuri.org/ITrafficPoliceService/GetDriverOwnerByIdResponse")]
        System.IAsyncResult BeginGetDriverOwnerById(string id, System.AsyncCallback callback, object asyncState);
        
        TrafficPolice.Core.TrafficPoliceReference.DriverOwner EndGetDriverOwnerById(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ITrafficPoliceService/getRegByRegNum", ReplyAction="http://tempuri.org/ITrafficPoliceService/getRegByRegNumResponse")]
        System.IAsyncResult BegingetRegByRegNum(string regNum, System.AsyncCallback callback, object asyncState);
        
        TrafficPolice.Core.TrafficPoliceReference.Registration EndgetRegByRegNum(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ITrafficPoliceService/addPenaltyToDriverOwner", ReplyAction="http://tempuri.org/ITrafficPoliceService/addPenaltyToDriverOwnerResponse")]
        System.IAsyncResult BeginaddPenaltyToDriverOwner(TrafficPolice.Core.TrafficPoliceReference.Penalty pen, System.AsyncCallback callback, object asyncState);
        
        string EndaddPenaltyToDriverOwner(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITrafficPoliceServiceChannel : TrafficPolice.Core.TrafficPoliceReference.ITrafficPoliceService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetUserByIdAndPassCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetUserByIdAndPassCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public TrafficPolice.Core.TrafficPoliceReference.User Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((TrafficPolice.Core.TrafficPoliceReference.User)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetDriverOwnerByIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetDriverOwnerByIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public TrafficPolice.Core.TrafficPoliceReference.DriverOwner Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((TrafficPolice.Core.TrafficPoliceReference.DriverOwner)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class getRegByRegNumCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public getRegByRegNumCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public TrafficPolice.Core.TrafficPoliceReference.Registration Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((TrafficPolice.Core.TrafficPoliceReference.Registration)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class addPenaltyToDriverOwnerCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public addPenaltyToDriverOwnerCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TrafficPoliceServiceClient : System.ServiceModel.ClientBase<TrafficPolice.Core.TrafficPoliceReference.ITrafficPoliceService>, TrafficPolice.Core.TrafficPoliceReference.ITrafficPoliceService {
        
        private BeginOperationDelegate onBeginGetUserByIdAndPassDelegate;
        
        private EndOperationDelegate onEndGetUserByIdAndPassDelegate;
        
        private System.Threading.SendOrPostCallback onGetUserByIdAndPassCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetDriverOwnerByIdDelegate;
        
        private EndOperationDelegate onEndGetDriverOwnerByIdDelegate;
        
        private System.Threading.SendOrPostCallback onGetDriverOwnerByIdCompletedDelegate;
        
        private BeginOperationDelegate onBegingetRegByRegNumDelegate;
        
        private EndOperationDelegate onEndgetRegByRegNumDelegate;
        
        private System.Threading.SendOrPostCallback ongetRegByRegNumCompletedDelegate;
        
        private BeginOperationDelegate onBeginaddPenaltyToDriverOwnerDelegate;
        
        private EndOperationDelegate onEndaddPenaltyToDriverOwnerDelegate;
        
        private System.Threading.SendOrPostCallback onaddPenaltyToDriverOwnerCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public TrafficPoliceServiceClient() : 
                base(TrafficPoliceServiceClient.GetDefaultBinding(), TrafficPoliceServiceClient.GetDefaultEndpointAddress()) {
        }
        
        public TrafficPoliceServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(TrafficPoliceServiceClient.GetBindingForEndpoint(endpointConfiguration), TrafficPoliceServiceClient.GetEndpointAddress(endpointConfiguration)) {
        }
        
        public TrafficPoliceServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(TrafficPoliceServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress)) {
        }
        
        public TrafficPoliceServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(TrafficPoliceServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress) {
        }
        
        public TrafficPoliceServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<GetUserByIdAndPassCompletedEventArgs> GetUserByIdAndPassCompleted;
        
        public event System.EventHandler<GetDriverOwnerByIdCompletedEventArgs> GetDriverOwnerByIdCompleted;
        
        public event System.EventHandler<getRegByRegNumCompletedEventArgs> getRegByRegNumCompleted;
        
        public event System.EventHandler<addPenaltyToDriverOwnerCompletedEventArgs> addPenaltyToDriverOwnerCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult TrafficPolice.Core.TrafficPoliceReference.ITrafficPoliceService.BeginGetUserByIdAndPass(string id, string password, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetUserByIdAndPass(id, password, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TrafficPolice.Core.TrafficPoliceReference.User TrafficPolice.Core.TrafficPoliceReference.ITrafficPoliceService.EndGetUserByIdAndPass(System.IAsyncResult result) {
            return base.Channel.EndGetUserByIdAndPass(result);
        }
        
        private System.IAsyncResult OnBeginGetUserByIdAndPass(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string id = ((string)(inValues[0]));
            string password = ((string)(inValues[1]));
            return ((TrafficPolice.Core.TrafficPoliceReference.ITrafficPoliceService)(this)).BeginGetUserByIdAndPass(id, password, callback, asyncState);
        }
        
        private object[] OnEndGetUserByIdAndPass(System.IAsyncResult result) {
            TrafficPolice.Core.TrafficPoliceReference.User retVal = ((TrafficPolice.Core.TrafficPoliceReference.ITrafficPoliceService)(this)).EndGetUserByIdAndPass(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetUserByIdAndPassCompleted(object state) {
            if ((this.GetUserByIdAndPassCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetUserByIdAndPassCompleted(this, new GetUserByIdAndPassCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetUserByIdAndPassAsync(string id, string password) {
            this.GetUserByIdAndPassAsync(id, password, null);
        }
        
        public void GetUserByIdAndPassAsync(string id, string password, object userState) {
            if ((this.onBeginGetUserByIdAndPassDelegate == null)) {
                this.onBeginGetUserByIdAndPassDelegate = new BeginOperationDelegate(this.OnBeginGetUserByIdAndPass);
            }
            if ((this.onEndGetUserByIdAndPassDelegate == null)) {
                this.onEndGetUserByIdAndPassDelegate = new EndOperationDelegate(this.OnEndGetUserByIdAndPass);
            }
            if ((this.onGetUserByIdAndPassCompletedDelegate == null)) {
                this.onGetUserByIdAndPassCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetUserByIdAndPassCompleted);
            }
            base.InvokeAsync(this.onBeginGetUserByIdAndPassDelegate, new object[] {
                        id,
                        password}, this.onEndGetUserByIdAndPassDelegate, this.onGetUserByIdAndPassCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult TrafficPolice.Core.TrafficPoliceReference.ITrafficPoliceService.BeginGetDriverOwnerById(string id, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetDriverOwnerById(id, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TrafficPolice.Core.TrafficPoliceReference.DriverOwner TrafficPolice.Core.TrafficPoliceReference.ITrafficPoliceService.EndGetDriverOwnerById(System.IAsyncResult result) {
            return base.Channel.EndGetDriverOwnerById(result);
        }
        
        private System.IAsyncResult OnBeginGetDriverOwnerById(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string id = ((string)(inValues[0]));
            return ((TrafficPolice.Core.TrafficPoliceReference.ITrafficPoliceService)(this)).BeginGetDriverOwnerById(id, callback, asyncState);
        }
        
        private object[] OnEndGetDriverOwnerById(System.IAsyncResult result) {
            TrafficPolice.Core.TrafficPoliceReference.DriverOwner retVal = ((TrafficPolice.Core.TrafficPoliceReference.ITrafficPoliceService)(this)).EndGetDriverOwnerById(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetDriverOwnerByIdCompleted(object state) {
            if ((this.GetDriverOwnerByIdCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetDriverOwnerByIdCompleted(this, new GetDriverOwnerByIdCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetDriverOwnerByIdAsync(string id) {
            this.GetDriverOwnerByIdAsync(id, null);
        }
        
        public void GetDriverOwnerByIdAsync(string id, object userState) {
            if ((this.onBeginGetDriverOwnerByIdDelegate == null)) {
                this.onBeginGetDriverOwnerByIdDelegate = new BeginOperationDelegate(this.OnBeginGetDriverOwnerById);
            }
            if ((this.onEndGetDriverOwnerByIdDelegate == null)) {
                this.onEndGetDriverOwnerByIdDelegate = new EndOperationDelegate(this.OnEndGetDriverOwnerById);
            }
            if ((this.onGetDriverOwnerByIdCompletedDelegate == null)) {
                this.onGetDriverOwnerByIdCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetDriverOwnerByIdCompleted);
            }
            base.InvokeAsync(this.onBeginGetDriverOwnerByIdDelegate, new object[] {
                        id}, this.onEndGetDriverOwnerByIdDelegate, this.onGetDriverOwnerByIdCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult TrafficPolice.Core.TrafficPoliceReference.ITrafficPoliceService.BegingetRegByRegNum(string regNum, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BegingetRegByRegNum(regNum, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TrafficPolice.Core.TrafficPoliceReference.Registration TrafficPolice.Core.TrafficPoliceReference.ITrafficPoliceService.EndgetRegByRegNum(System.IAsyncResult result) {
            return base.Channel.EndgetRegByRegNum(result);
        }
        
        private System.IAsyncResult OnBegingetRegByRegNum(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string regNum = ((string)(inValues[0]));
            return ((TrafficPolice.Core.TrafficPoliceReference.ITrafficPoliceService)(this)).BegingetRegByRegNum(regNum, callback, asyncState);
        }
        
        private object[] OnEndgetRegByRegNum(System.IAsyncResult result) {
            TrafficPolice.Core.TrafficPoliceReference.Registration retVal = ((TrafficPolice.Core.TrafficPoliceReference.ITrafficPoliceService)(this)).EndgetRegByRegNum(result);
            return new object[] {
                    retVal};
        }
        
        private void OngetRegByRegNumCompleted(object state) {
            if ((this.getRegByRegNumCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.getRegByRegNumCompleted(this, new getRegByRegNumCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void getRegByRegNumAsync(string regNum) {
            this.getRegByRegNumAsync(regNum, null);
        }
        
        public void getRegByRegNumAsync(string regNum, object userState) {
            if ((this.onBegingetRegByRegNumDelegate == null)) {
                this.onBegingetRegByRegNumDelegate = new BeginOperationDelegate(this.OnBegingetRegByRegNum);
            }
            if ((this.onEndgetRegByRegNumDelegate == null)) {
                this.onEndgetRegByRegNumDelegate = new EndOperationDelegate(this.OnEndgetRegByRegNum);
            }
            if ((this.ongetRegByRegNumCompletedDelegate == null)) {
                this.ongetRegByRegNumCompletedDelegate = new System.Threading.SendOrPostCallback(this.OngetRegByRegNumCompleted);
            }
            base.InvokeAsync(this.onBegingetRegByRegNumDelegate, new object[] {
                        regNum}, this.onEndgetRegByRegNumDelegate, this.ongetRegByRegNumCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult TrafficPolice.Core.TrafficPoliceReference.ITrafficPoliceService.BeginaddPenaltyToDriverOwner(TrafficPolice.Core.TrafficPoliceReference.Penalty pen, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginaddPenaltyToDriverOwner(pen, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        string TrafficPolice.Core.TrafficPoliceReference.ITrafficPoliceService.EndaddPenaltyToDriverOwner(System.IAsyncResult result) {
            return base.Channel.EndaddPenaltyToDriverOwner(result);
        }
        
        private System.IAsyncResult OnBeginaddPenaltyToDriverOwner(object[] inValues, System.AsyncCallback callback, object asyncState) {
            TrafficPolice.Core.TrafficPoliceReference.Penalty pen = ((TrafficPolice.Core.TrafficPoliceReference.Penalty)(inValues[0]));
            return ((TrafficPolice.Core.TrafficPoliceReference.ITrafficPoliceService)(this)).BeginaddPenaltyToDriverOwner(pen, callback, asyncState);
        }
        
        private object[] OnEndaddPenaltyToDriverOwner(System.IAsyncResult result) {
            string retVal = ((TrafficPolice.Core.TrafficPoliceReference.ITrafficPoliceService)(this)).EndaddPenaltyToDriverOwner(result);
            return new object[] {
                    retVal};
        }
        
        private void OnaddPenaltyToDriverOwnerCompleted(object state) {
            if ((this.addPenaltyToDriverOwnerCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.addPenaltyToDriverOwnerCompleted(this, new addPenaltyToDriverOwnerCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void addPenaltyToDriverOwnerAsync(TrafficPolice.Core.TrafficPoliceReference.Penalty pen) {
            this.addPenaltyToDriverOwnerAsync(pen, null);
        }
        
        public void addPenaltyToDriverOwnerAsync(TrafficPolice.Core.TrafficPoliceReference.Penalty pen, object userState) {
            if ((this.onBeginaddPenaltyToDriverOwnerDelegate == null)) {
                this.onBeginaddPenaltyToDriverOwnerDelegate = new BeginOperationDelegate(this.OnBeginaddPenaltyToDriverOwner);
            }
            if ((this.onEndaddPenaltyToDriverOwnerDelegate == null)) {
                this.onEndaddPenaltyToDriverOwnerDelegate = new EndOperationDelegate(this.OnEndaddPenaltyToDriverOwner);
            }
            if ((this.onaddPenaltyToDriverOwnerCompletedDelegate == null)) {
                this.onaddPenaltyToDriverOwnerCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnaddPenaltyToDriverOwnerCompleted);
            }
            base.InvokeAsync(this.onBeginaddPenaltyToDriverOwnerDelegate, new object[] {
                        pen}, this.onEndaddPenaltyToDriverOwnerDelegate, this.onaddPenaltyToDriverOwnerCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override TrafficPolice.Core.TrafficPoliceReference.ITrafficPoliceService CreateChannel() {
            return new TrafficPoliceServiceClientChannel(this);
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ITrafficPoliceService)) {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.MaxReceivedMessageSize = int.MaxValue;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ITrafficPoliceService)) {
                return new System.ServiceModel.EndpointAddress("http://localhost:9607/TrafficPoliceService.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding() {
            return TrafficPoliceServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_ITrafficPoliceService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress() {
            return TrafficPoliceServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_ITrafficPoliceService);
        }
        
        private class TrafficPoliceServiceClientChannel : ChannelBase<TrafficPolice.Core.TrafficPoliceReference.ITrafficPoliceService>, TrafficPolice.Core.TrafficPoliceReference.ITrafficPoliceService {
            
            public TrafficPoliceServiceClientChannel(System.ServiceModel.ClientBase<TrafficPolice.Core.TrafficPoliceReference.ITrafficPoliceService> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginGetUserByIdAndPass(string id, string password, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = id;
                _args[1] = password;
                System.IAsyncResult _result = base.BeginInvoke("GetUserByIdAndPass", _args, callback, asyncState);
                return _result;
            }
            
            public TrafficPolice.Core.TrafficPoliceReference.User EndGetUserByIdAndPass(System.IAsyncResult result) {
                object[] _args = new object[0];
                TrafficPolice.Core.TrafficPoliceReference.User _result = ((TrafficPolice.Core.TrafficPoliceReference.User)(base.EndInvoke("GetUserByIdAndPass", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetDriverOwnerById(string id, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = id;
                System.IAsyncResult _result = base.BeginInvoke("GetDriverOwnerById", _args, callback, asyncState);
                return _result;
            }
            
            public TrafficPolice.Core.TrafficPoliceReference.DriverOwner EndGetDriverOwnerById(System.IAsyncResult result) {
                object[] _args = new object[0];
                TrafficPolice.Core.TrafficPoliceReference.DriverOwner _result = ((TrafficPolice.Core.TrafficPoliceReference.DriverOwner)(base.EndInvoke("GetDriverOwnerById", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BegingetRegByRegNum(string regNum, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = regNum;
                System.IAsyncResult _result = base.BeginInvoke("getRegByRegNum", _args, callback, asyncState);
                return _result;
            }
            
            public TrafficPolice.Core.TrafficPoliceReference.Registration EndgetRegByRegNum(System.IAsyncResult result) {
                object[] _args = new object[0];
                TrafficPolice.Core.TrafficPoliceReference.Registration _result = ((TrafficPolice.Core.TrafficPoliceReference.Registration)(base.EndInvoke("getRegByRegNum", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginaddPenaltyToDriverOwner(TrafficPolice.Core.TrafficPoliceReference.Penalty pen, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = pen;
                System.IAsyncResult _result = base.BeginInvoke("addPenaltyToDriverOwner", _args, callback, asyncState);
                return _result;
            }
            
            public string EndaddPenaltyToDriverOwner(System.IAsyncResult result) {
                object[] _args = new object[0];
                string _result = ((string)(base.EndInvoke("addPenaltyToDriverOwner", _args, result)));
                return _result;
            }
        }
        
        public enum EndpointConfiguration {
            
            BasicHttpBinding_ITrafficPoliceService,
        }
    }
}
