#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("TrafficPolice.UI.Droid.Resource", IsApplication=true)]

namespace TrafficPolice.UI.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxBind = global::TrafficPolice.UI.Droid.Resource.Attribute.MvxBind;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxDropDownItemTemplate = global::TrafficPolice.UI.Droid.Resource.Attribute.MvxDropDownItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxGroupItemTemplate = global::TrafficPolice.UI.Droid.Resource.Attribute.MvxGroupItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxItemTemplate = global::TrafficPolice.UI.Droid.Resource.Attribute.MvxItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxLang = global::TrafficPolice.UI.Droid.Resource.Attribute.MvxLang;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxSource = global::TrafficPolice.UI.Droid.Resource.Attribute.MvxSource;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxTemplate = global::TrafficPolice.UI.Droid.Resource.Attribute.MvxTemplate;
			global::MvvmCross.Binding.Droid.Resource.Id.MvvmCrossTagId = global::TrafficPolice.UI.Droid.Resource.Id.MvvmCrossTagId;
			global::MvvmCross.Binding.Droid.Resource.Id.MvxBindingTagUnique = global::TrafficPolice.UI.Droid.Resource.Id.MvxBindingTagUnique;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxBinding = global::TrafficPolice.UI.Droid.Resource.Styleable.MvxBinding;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxBinding_MvxBind = global::TrafficPolice.UI.Droid.Resource.Styleable.MvxBinding_MvxBind;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxBinding_MvxLang = global::TrafficPolice.UI.Droid.Resource.Styleable.MvxBinding_MvxLang;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxControl = global::TrafficPolice.UI.Droid.Resource.Styleable.MvxControl;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxControl_MvxTemplate = global::TrafficPolice.UI.Droid.Resource.Styleable.MvxControl_MvxTemplate;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxExpandableListView = global::TrafficPolice.UI.Droid.Resource.Styleable.MvxExpandableListView;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxExpandableListView_MvxGroupItemTemplate = global::TrafficPolice.UI.Droid.Resource.Styleable.MvxExpandableListView_MvxGroupItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxImageView = global::TrafficPolice.UI.Droid.Resource.Styleable.MvxImageView;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxImageView_MvxSource = global::TrafficPolice.UI.Droid.Resource.Styleable.MvxImageView_MvxSource;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxListView = global::TrafficPolice.UI.Droid.Resource.Styleable.MvxListView;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxListView_MvxDropDownItemTemplate = global::TrafficPolice.UI.Droid.Resource.Styleable.MvxListView_MvxDropDownItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxListView_MvxItemTemplate = global::TrafficPolice.UI.Droid.Resource.Styleable.MvxListView_MvxItemTemplate;
			global::MvvmCross.Droid.FullFragging.Resource.Attribute.MvxBind = global::TrafficPolice.UI.Droid.Resource.Attribute.MvxBind;
			global::MvvmCross.Droid.FullFragging.Resource.Attribute.MvxDropDownItemTemplate = global::TrafficPolice.UI.Droid.Resource.Attribute.MvxDropDownItemTemplate;
			global::MvvmCross.Droid.FullFragging.Resource.Attribute.MvxGroupItemTemplate = global::TrafficPolice.UI.Droid.Resource.Attribute.MvxGroupItemTemplate;
			global::MvvmCross.Droid.FullFragging.Resource.Attribute.MvxItemTemplate = global::TrafficPolice.UI.Droid.Resource.Attribute.MvxItemTemplate;
			global::MvvmCross.Droid.FullFragging.Resource.Attribute.MvxLang = global::TrafficPolice.UI.Droid.Resource.Attribute.MvxLang;
			global::MvvmCross.Droid.FullFragging.Resource.Attribute.MvxSource = global::TrafficPolice.UI.Droid.Resource.Attribute.MvxSource;
			global::MvvmCross.Droid.FullFragging.Resource.Attribute.MvxTemplate = global::TrafficPolice.UI.Droid.Resource.Attribute.MvxTemplate;
			global::MvvmCross.Droid.FullFragging.Resource.Id.MvvmCrossTagId = global::TrafficPolice.UI.Droid.Resource.Id.MvvmCrossTagId;
			global::MvvmCross.Droid.FullFragging.Resource.Id.MvxBindingTagUnique = global::TrafficPolice.UI.Droid.Resource.Id.MvxBindingTagUnique;
			global::MvvmCross.Droid.FullFragging.Resource.Styleable.MvxBinding = global::TrafficPolice.UI.Droid.Resource.Styleable.MvxBinding;
			global::MvvmCross.Droid.FullFragging.Resource.Styleable.MvxBinding_MvxBind = global::TrafficPolice.UI.Droid.Resource.Styleable.MvxBinding_MvxBind;
			global::MvvmCross.Droid.FullFragging.Resource.Styleable.MvxBinding_MvxLang = global::TrafficPolice.UI.Droid.Resource.Styleable.MvxBinding_MvxLang;
			global::MvvmCross.Droid.FullFragging.Resource.Styleable.MvxControl = global::TrafficPolice.UI.Droid.Resource.Styleable.MvxControl;
			global::MvvmCross.Droid.FullFragging.Resource.Styleable.MvxControl_MvxTemplate = global::TrafficPolice.UI.Droid.Resource.Styleable.MvxControl_MvxTemplate;
			global::MvvmCross.Droid.FullFragging.Resource.Styleable.MvxExpandableListView = global::TrafficPolice.UI.Droid.Resource.Styleable.MvxExpandableListView;
			global::MvvmCross.Droid.FullFragging.Resource.Styleable.MvxExpandableListView_MvxGroupItemTemplate = global::TrafficPolice.UI.Droid.Resource.Styleable.MvxExpandableListView_MvxGroupItemTemplate;
			global::MvvmCross.Droid.FullFragging.Resource.Styleable.MvxImageView = global::TrafficPolice.UI.Droid.Resource.Styleable.MvxImageView;
			global::MvvmCross.Droid.FullFragging.Resource.Styleable.MvxImageView_MvxSource = global::TrafficPolice.UI.Droid.Resource.Styleable.MvxImageView_MvxSource;
			global::MvvmCross.Droid.FullFragging.Resource.Styleable.MvxListView = global::TrafficPolice.UI.Droid.Resource.Styleable.MvxListView;
			global::MvvmCross.Droid.FullFragging.Resource.Styleable.MvxListView_MvxDropDownItemTemplate = global::TrafficPolice.UI.Droid.Resource.Styleable.MvxListView_MvxDropDownItemTemplate;
			global::MvvmCross.Droid.FullFragging.Resource.Styleable.MvxListView_MvxItemTemplate = global::TrafficPolice.UI.Droid.Resource.Styleable.MvxListView_MvxItemTemplate;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int MvxBind = 2130771968;
			
			// aapt resource value: 0x7f010004
			public const int MvxDropDownItemTemplate = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int MvxGroupItemTemplate = 2130771973;
			
			// aapt resource value: 0x7f010003
			public const int MvxItemTemplate = 2130771971;
			
			// aapt resource value: 0x7f010001
			public const int MvxLang = 2130771969;
			
			// aapt resource value: 0x7f010006
			public const int MvxSource = 2130771974;
			
			// aapt resource value: 0x7f010002
			public const int MvxTemplate = 2130771970;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050007
			public const int amarelo_corrige = 2131034119;
			
			// aapt resource value: 0x7f050001
			public const int black = 2131034113;
			
			// aapt resource value: 0x7f050003
			public const int blue_background = 2131034115;
			
			// aapt resource value: 0x7f050006
			public const int branco = 2131034118;
			
			// aapt resource value: 0x7f050004
			public const int dark_blue = 2131034116;
			
			// aapt resource value: 0x7f050002
			public const int semi_transparent_white = 2131034114;
			
			// aapt resource value: 0x7f050005
			public const int verde_claro_fundo_lista = 2131034117;
			
			// aapt resource value: 0x7f050008
			public const int verde_confirma = 2131034120;
			
			// aapt resource value: 0x7f050000
			public const int white = 2131034112;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int appbar_camera = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int appbar_clear_inverse_reflect_horizontal = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int appbar_delete = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int appbar_image_gallery = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int appbar_phone = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Icon = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int kat = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int navigation_background = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int navigation_background_landscape = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int semi_transp_edit_text = 2130837513;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f040000
			public const int MvvmCrossTagId = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int MvxBindingTagUnique = 2130968577;
			
			// aapt resource value: 0x7f040035
			public const int address_label = 2130968629;
			
			// aapt resource value: 0x7f040034
			public const int address_static_label = 2130968628;
			
			// aapt resource value: 0x7f04003c
			public const int buttons_layout = 2130968636;
			
			// aapt resource value: 0x7f040045
			public const int checkBox1 = 2130968645;
			
			// aapt resource value: 0x7f040049
			public const int checkBox_civil = 2130968649;
			
			// aapt resource value: 0x7f040051
			public const int checkBox_damage = 2130968657;
			
			// aapt resource value: 0x7f040041
			public const int choose_pic_btn = 2130968641;
			
			// aapt resource value: 0x7f040031
			public const int citizenship_label = 2130968625;
			
			// aapt resource value: 0x7f040030
			public const int citizenship_static_label = 2130968624;
			
			// aapt resource value: 0x7f04003d
			public const int clear_btn = 2130968637;
			
			// aapt resource value: 0x7f040067
			public const int color_field = 2130968679;
			
			// aapt resource value: 0x7f040069
			public const int color_info_label = 2130968681;
			
			// aapt resource value: 0x7f040068
			public const int color_static_label = 2130968680;
			
			// aapt resource value: 0x7f04005e
			public const int cubic_field = 2130968670;
			
			// aapt resource value: 0x7f040062
			public const int cubic_helper_label = 2130968674;
			
			// aapt resource value: 0x7f040061
			public const int cubic_info_label = 2130968673;
			
			// aapt resource value: 0x7f040060
			public const int cubic_layout = 2130968672;
			
			// aapt resource value: 0x7f04005f
			public const int cubic_static_label = 2130968671;
			
			// aapt resource value: 0x7f040072
			public const int currentreg_date_txt = 2130968690;
			
			// aapt resource value: 0x7f040071
			public const int currentreg_static_label = 2130968689;
			
			// aapt resource value: 0x7f040012
			public const int doc_issued_by_lbl = 2130968594;
			
			// aapt resource value: 0x7f040023
			public const int doc_issued_label = 2130968611;
			
			// aapt resource value: 0x7f04002d
			public const int driver_firstname_lbl = 2130968621;
			
			// aapt resource value: 0x7f04002c
			public const int driver_label = 2130968620;
			
			// aapt resource value: 0x7f04002f
			public const int driver_lastname_lbl = 2130968623;
			
			// aapt resource value: 0x7f040032
			public const int driver_phone_number_layout = 2130968626;
			
			// aapt resource value: 0x7f04002e
			public const int driver_secondname_lbl = 2130968622;
			
			// aapt resource value: 0x7f040078
			public const int driverowner = 2130968696;
			
			// aapt resource value: 0x7f040020
			public const int enter_btn = 2130968608;
			
			// aapt resource value: 0x7f04001d
			public const int error_info_lbl = 2130968605;
			
			// aapt resource value: 0x7f04001c
			public const int error_lbl = 2130968604;
			
			// aapt resource value: 0x7f040013
			public const int expiry_date_txt = 2130968595;
			
			// aapt resource value: 0x7f040050
			public const int field_car_insurance = 2130968656;
			
			// aapt resource value: 0x7f040054
			public const int field_tech_details = 2130968660;
			
			// aapt resource value: 0x7f040070
			public const int firstreg_date_txt = 2130968688;
			
			// aapt resource value: 0x7f04006f
			public const int firstreg_static_label = 2130968687;
			
			// aapt resource value: 0x7f04000f
			public const int happened_date_label = 2130968591;
			
			// aapt resource value: 0x7f040010
			public const int happened_date_txt = 2130968592;
			
			// aapt resource value: 0x7f04000e
			public const int happened_penalty_date_layout = 2130968590;
			
			// aapt resource value: 0x7f04001b
			public const int info_label = 2130968603;
			
			// aapt resource value: 0x7f040052
			public const int insurer_static_label = 2130968658;
			
			// aapt resource value: 0x7f040025
			public const int issued_date_layout = 2130968613;
			
			// aapt resource value: 0x7f04004d
			public const int issued_date_txt = 2130968653;
			
			// aapt resource value: 0x7f04000d
			public const int issued_registered_dates_dates_layout = 2130968589;
			
			// aapt resource value: 0x7f040009
			public const int issuer_details_layout = 2130968585;
			
			// aapt resource value: 0x7f04000b
			public const int issuer_id_label = 2130968587;
			
			// aapt resource value: 0x7f04000a
			public const int issuer_id_static_label = 2130968586;
			
			// aapt resource value: 0x7f04004b
			public const int issuer_label = 2130968651;
			
			// aapt resource value: 0x7f04004a
			public const int issuer_static_label = 2130968650;
			
			// aapt resource value: 0x7f040038
			public const int kat = 2130968632;
			
			// aapt resource value: 0x7f04004e
			public const int liability_Valid_label = 2130968654;
			
			// aapt resource value: 0x7f04004c
			public const int liability_issued_label = 2130968652;
			
			// aapt resource value: 0x7f04000c
			public const int location_info_label = 2130968588;
			
			// aapt resource value: 0x7f040077
			public const int logout = 2130968695;
			
			// aapt resource value: 0x7f04001a
			public const int main_layout = 2130968602;
			
			// aapt resource value: 0x7f040055
			public const int manufacturer_field = 2130968661;
			
			// aapt resource value: 0x7f040057
			public const int manufacturer_info_label = 2130968663;
			
			// aapt resource value: 0x7f040056
			public const int manufacturer_static_label = 2130968662;
			
			// aapt resource value: 0x7f040074
			public const int map = 2130968692;
			
			// aapt resource value: 0x7f040058
			public const int model_field = 2130968664;
			
			// aapt resource value: 0x7f04005a
			public const int model_info_label = 2130968666;
			
			// aapt resource value: 0x7f040059
			public const int model_static_label = 2130968665;
			
			// aapt resource value: 0x7f04006e
			public const int ownerid_info_label = 2130968686;
			
			// aapt resource value: 0x7f04006d
			public const int ownerid_static_label = 2130968685;
			
			// aapt resource value: 0x7f04003a
			public const int password_label = 2130968634;
			
			// aapt resource value: 0x7f04003b
			public const int password_txt = 2130968635;
			
			// aapt resource value: 0x7f040076
			public const int penalty = 2130968694;
			
			// aapt resource value: 0x7f040006
			public const int penalty_data_layout = 2130968582;
			
			// aapt resource value: 0x7f040016
			public const int penalty_desc_info_txt = 2130968598;
			
			// aapt resource value: 0x7f040015
			public const int penalty_desc_layout = 2130968597;
			
			// aapt resource value: 0x7f040007
			public const int penalty_desc_static_label = 2130968583;
			
			// aapt resource value: 0x7f040018
			public const int penalty_protest_layout = 2130968600;
			
			// aapt resource value: 0x7f040019
			public const int penalty_protest_static_label = 2130968601;
			
			// aapt resource value: 0x7f040033
			public const int phone_number_label = 2130968627;
			
			// aapt resource value: 0x7f040063
			public const int power_field = 2130968675;
			
			// aapt resource value: 0x7f040066
			public const int power_helper_label = 2130968678;
			
			// aapt resource value: 0x7f040065
			public const int power_info_label = 2130968677;
			
			// aapt resource value: 0x7f040064
			public const int power_static_label = 2130968676;
			
			// aapt resource value: 0x7f040039
			public const int private_number_label = 2130968633;
			
			// aapt resource value: 0x7f04001f
			public const int progressBar = 2130968607;
			
			// aapt resource value: 0x7f040029
			public const int progressBar2 = 2130968617;
			
			// aapt resource value: 0x7f04001e
			public const int progress_bar_layout = 2130968606;
			
			// aapt resource value: 0x7f04003e
			public const int reg_num_static_label = 2130968638;
			
			// aapt resource value: 0x7f04003f
			public const int reg_num_txt = 2130968639;
			
			// aapt resource value: 0x7f040011
			public const int registered_date_layout = 2130968593;
			
			// aapt resource value: 0x7f040040
			public const int registration_buttons_layout = 2130968640;
			
			// aapt resource value: 0x7f040004
			public const int regnum_info_label = 2130968580;
			
			// aapt resource value: 0x7f040075
			public const int relocation = 2130968693;
			
			// aapt resource value: 0x7f040028
			public const int remaining_points_lbl = 2130968616;
			
			// aapt resource value: 0x7f040073
			public const int save = 2130968691;
			
			// aapt resource value: 0x7f040002
			public const int searchImageButton = 2130968578;
			
			// aapt resource value: 0x7f04002a
			public const int tab_categories = 2130968618;
			
			// aapt resource value: 0x7f04006c
			public const int tab_common_data = 2130968684;
			
			// aapt resource value: 0x7f040043
			public const int tab_insurance = 2130968643;
			
			// aapt resource value: 0x7f040048
			public const int tab_liability = 2130968648;
			
			// aapt resource value: 0x7f040022
			public const int tab_licence = 2130968610;
			
			// aapt resource value: 0x7f040005
			public const int tab_penalty_data = 2130968581;
			
			// aapt resource value: 0x7f040014
			public const int tab_penalty_description = 2130968596;
			
			// aapt resource value: 0x7f040017
			public const int tab_penalty_protest = 2130968599;
			
			// aapt resource value: 0x7f04002b
			public const int tab_personal_data = 2130968619;
			
			// aapt resource value: 0x7f040053
			public const int tab_tech_details = 2130968659;
			
			// aapt resource value: 0x7f040003
			public const int tabhost = 2130968579;
			
			// aapt resource value: 0x7f040042
			public const int take_pic_btn = 2130968642;
			
			// aapt resource value: 0x7f040036
			public const int title_layout = 2130968630;
			
			// aapt resource value: 0x7f04005b
			public const int type_field = 2130968667;
			
			// aapt resource value: 0x7f04005d
			public const int type_info_label = 2130968669;
			
			// aapt resource value: 0x7f04005c
			public const int type_static_label = 2130968668;
			
			// aapt resource value: 0x7f040008
			public const int user_id_txt = 2130968584;
			
			// aapt resource value: 0x7f040021
			public const int user_info_label = 2130968609;
			
			// aapt resource value: 0x7f04004f
			public const int valid_date_txt = 2130968655;
			
			// aapt resource value: 0x7f040026
			public const int valid_from_lbl = 2130968614;
			
			// aapt resource value: 0x7f040047
			public const int valid_until_static_label = 2130968647;
			
			// aapt resource value: 0x7f040027
			public const int validity_date_txt = 2130968615;
			
			// aapt resource value: 0x7f040024
			public const int validity_dates_layout = 2130968612;
			
			// aapt resource value: 0x7f040037
			public const int vhod = 2130968631;
			
			// aapt resource value: 0x7f040044
			public const int vignette_field = 2130968644;
			
			// aapt resource value: 0x7f040046
			public const int vignette_layout = 2130968646;
			
			// aapt resource value: 0x7f04006b
			public const int vin_info_label = 2130968683;
			
			// aapt resource value: 0x7f04006a
			public const int vin_static_label = 2130968682;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Category_Item = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Navigation_Toolbar = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int View_AddPenalty = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int View_DriverOwnerChild = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int View_DriverOwnerDetails = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int View_Login = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int View_Navigation = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int View_RegistrationChild = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int View_RegistrationDetails = 2130903048;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f070000
			public const int add_penalty_menu = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int driverowner_navigation_menu = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int navigation_menu = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int registration_navigation_menu = 2131165187;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060001
			public const int ApplicationName = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int Hello = 2131099648;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] MvxBinding = new int[] {
					2130771968,
					2130771969};
			
			// aapt resource value: 0
			public const int MvxBinding_MvxBind = 0;
			
			// aapt resource value: 1
			public const int MvxBinding_MvxLang = 1;
			
			public static int[] MvxControl = new int[] {
					2130771970};
			
			// aapt resource value: 0
			public const int MvxControl_MvxTemplate = 0;
			
			public static int[] MvxExpandableListView = new int[] {
					2130771973};
			
			// aapt resource value: 0
			public const int MvxExpandableListView_MvxGroupItemTemplate = 0;
			
			public static int[] MvxImageView = new int[] {
					2130771974};
			
			// aapt resource value: 0
			public const int MvxImageView_MvxSource = 0;
			
			public static int[] MvxListView = new int[] {
					2130771971,
					2130771972};
			
			// aapt resource value: 1
			public const int MvxListView_MvxDropDownItemTemplate = 1;
			
			// aapt resource value: 0
			public const int MvxListView_MvxItemTemplate = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
